/*
 * Vorboss Product Availability API
 * This API is provided by Vorboss to allow customers to check which products are available at a given postcode.
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package Com.Vorboss.ProductAvailability;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PostcodeAvailableProducts
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-10T11:59:02.518631+01:00[Europe/London]")

public class PostcodeAvailableProducts {
  @SerializedName("name")
  private String name = null;

  @SerializedName("price")
  private Float price = null;

  @SerializedName("leadTimeDays")
  private Integer leadTimeDays = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("bandwidthProvisioned")
  private Integer bandwidthProvisioned = null;

  @SerializedName("bandwidthCapactity")
  private Integer bandwidthCapactity = null;

  @SerializedName("term")
  private Integer term = null;

  public PostcodeAvailableProducts name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(example = "10G Internet", description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PostcodeAvailableProducts price(Float price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @Schema(example = "550", description = "")
  public Float getPrice() {
    return price;
  }

  public void setPrice(Float price) {
    this.price = price;
  }

  public PostcodeAvailableProducts leadTimeDays(Integer leadTimeDays) {
    this.leadTimeDays = leadTimeDays;
    return this;
  }

   /**
   * Get leadTimeDays
   * @return leadTimeDays
  **/
  @Schema(example = "84", description = "")
  public Integer getLeadTimeDays() {
    return leadTimeDays;
  }

  public void setLeadTimeDays(Integer leadTimeDays) {
    this.leadTimeDays = leadTimeDays;
  }

  public PostcodeAvailableProducts currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @Schema(example = "GBP", description = "")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public PostcodeAvailableProducts bandwidthProvisioned(Integer bandwidthProvisioned) {
    this.bandwidthProvisioned = bandwidthProvisioned;
    return this;
  }

   /**
   * Get bandwidthProvisioned
   * @return bandwidthProvisioned
  **/
  @Schema(example = "1", description = "")
  public Integer getBandwidthProvisioned() {
    return bandwidthProvisioned;
  }

  public void setBandwidthProvisioned(Integer bandwidthProvisioned) {
    this.bandwidthProvisioned = bandwidthProvisioned;
  }

  public PostcodeAvailableProducts bandwidthCapactity(Integer bandwidthCapactity) {
    this.bandwidthCapactity = bandwidthCapactity;
    return this;
  }

   /**
   * Get bandwidthCapactity
   * @return bandwidthCapactity
  **/
  @Schema(example = "10", description = "")
  public Integer getBandwidthCapactity() {
    return bandwidthCapactity;
  }

  public void setBandwidthCapactity(Integer bandwidthCapactity) {
    this.bandwidthCapactity = bandwidthCapactity;
  }

  public PostcodeAvailableProducts term(Integer term) {
    this.term = term;
    return this;
  }

   /**
   * Get term
   * @return term
  **/
  @Schema(example = "12", description = "")
  public Integer getTerm() {
    return term;
  }

  public void setTerm(Integer term) {
    this.term = term;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostcodeAvailableProducts postcodeAvailableProducts = (PostcodeAvailableProducts) o;
    return Objects.equals(this.name, postcodeAvailableProducts.name) &&
        Objects.equals(this.price, postcodeAvailableProducts.price) &&
        Objects.equals(this.leadTimeDays, postcodeAvailableProducts.leadTimeDays) &&
        Objects.equals(this.currency, postcodeAvailableProducts.currency) &&
        Objects.equals(this.bandwidthProvisioned, postcodeAvailableProducts.bandwidthProvisioned) &&
        Objects.equals(this.bandwidthCapactity, postcodeAvailableProducts.bandwidthCapactity) &&
        Objects.equals(this.term, postcodeAvailableProducts.term);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, price, leadTimeDays, currency, bandwidthProvisioned, bandwidthCapactity, term);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostcodeAvailableProducts {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    leadTimeDays: ").append(toIndentedString(leadTimeDays)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    bandwidthProvisioned: ").append(toIndentedString(bandwidthProvisioned)).append("\n");
    sb.append("    bandwidthCapactity: ").append(toIndentedString(bandwidthCapactity)).append("\n");
    sb.append("    term: ").append(toIndentedString(term)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
