/*
 * Vorboss Product Availability API
 * This API is provided by Vorboss to allow customers to check which products are available at a given postcode.
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package Com.Vorboss.ProductAvailability;

import Com.Vorboss.ProductAvailability.Postcode;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ProductAvailabilityApi
 */
@Ignore
public class ProductAvailabilityApiTest {

    private final ProductAvailabilityApi api = new ProductAvailabilityApi();

    /**
     * Check a postcode
     *
     * Check which products are available at the given postcode.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void confirmPostcodeTest() throws Exception {
        String postcode = null;
        Postcode response = api.confirmPostcode(postcode);

        // TODO: test validations
    }
}
