/*
 * Vorboss Product Availability API
 * This API is provided by Vorboss to allow customers to check which products are available at a given postcode.
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package Com.Vorboss.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
